import type { AnalysisResult } from "../types/index.ts";

export class ReportBuilder {
  generate(analysis: AnalysisResult): string {
    const sections = [
      this.header(analysis),
      this.executiveSummary(analysis),
      this.scores(analysis),
      this.githubMetrics(analysis),
      this.communityIntelligence(analysis),
      this.codeQuality(analysis),
      this.insights(analysis),
      this.footer(analysis),
    ];

    return sections.join("\n\n");
  }

  private header(a: AnalysisResult): string {
    const date = new Date(a.analyzedAt).toLocaleString();
    const durationSeconds = (a.duration / 1000).toFixed(1);

    return `# 🔍 DevScout Analysis: ${a.repoName}

**Repository**: [${a.repoName}](${a.repoUrl})
**Analyzed**: ${date}
**Duration**: ${durationSeconds}s

---`;
  }

  private executiveSummary(a: AnalysisResult): string {
    const emoji = this.getScoreEmoji(a.scores.overall);
    const readyEmoji = a.productionReady ? "✅" : "⚠️";
    const readyText = a.productionReady ? "Yes" : "Needs Work";

    return `## 📊 Executive Summary

${a.summary}

**Overall Score**: ${a.scores.overall}/10 ${emoji}
**Production Ready**: ${readyEmoji} ${readyText}

---`;
  }

  private scores(a: AnalysisResult): string {
    return `## 📈 Scores

| Category | Score | Rating |
|----------|-------|--------|
| GitHub Health | ${a.scores.github}/10 ${this.getScoreEmoji(a.scores.github)} | ${
      this.getRating(a.scores.github)
    } |
| Community Sentiment | ${a.scores.community}/10 ${
      this.getScoreEmoji(a.scores.community)
    } | ${this.getRating(a.scores.community)} |
| Code Quality | ${a.scores.code}/10 ${this.getScoreEmoji(a.scores.code)} | ${
      this.getRating(a.scores.code)
    } |
| **Overall** | **${a.scores.overall}/10** ${this.getScoreEmoji(a.scores.overall)} | **${
      this.getRating(a.scores.overall)
    }** |

---`;
  }

  private githubMetrics(a: AnalysisResult): string {
    const openRatio = (a.github.openIssueRatio * 100).toFixed(1);

    return `## 📊 GitHub Metrics

| Metric | Value |
|--------|-------|
| ⭐ Stars | ${this.formatNumber(a.github.stars)} |
| 🔱 Forks | ${this.formatNumber(a.github.forks)} |
| 📂 Open Issues | ${a.github.openIssues} (${openRatio}%) |
| ✅ Closed Issues | ${a.github.closedIssues} |
| 💻 Language | ${a.github.language || "N/A"} |
| 🕐 Last Update | ${new Date(a.github.lastUpdate).toLocaleDateString()} |
| 🔧 Maintenance Score | ${a.github.maintenanceScore}/10 ${
      this.getScoreEmoji(a.github.maintenanceScore)
    } |

---`;
  }

  private communityIntelligence(a: AnalysisResult): string {
    const sentimentEmoji = this.getSentimentEmoji(a.web.overallSentiment);
    const complaints = a.web.complaints.length > 0
      ? a.web.complaints.map((c, i) => `${i + 1}. ${c}`).join("\n")
      : "_No significant complaints found_";
    const praise = a.web.praise.length > 0
      ? a.web.praise.map((p, i) => `${i + 1}. ${p}`).join("\n")
      : "_No significant praise found_";

    return `## 💬 Community Intelligence

**Sentiment**: ${a.web.overallSentiment} ${sentimentEmoji} (${a.web.sentimentScore.toFixed(2)})
**Reddit Mentions**: ${a.web.redditMentions}
**Hacker News Mentions**: ${a.web.hackerNewsMentions}

### 😞 Common Complaints
${complaints}

### 😊 Community Praise
${praise}

---`;
  }

  private codeQuality(a: AnalysisResult): string {
    const deps = a.code.dependencies.slice(0, 5);
    const depsList = deps.length > 0
      ? deps.map((d) => `- ${d.name} (${d.version})`).join("\n")
      : "_No dependencies found_";
    const moreText = a.code.dependencies.length > 5
      ? `\n_...and ${a.code.dependencies.length - 5} more_`
      : "";

    return `## 🔧 Code Quality

**Total Dependencies**: ${a.code.totalDependencies}
**Outdated Dependencies**: ${a.code.outdatedCount} (${a.code.outdatedPercentage.toFixed(1)}%)
**Risk Score**: ${a.code.riskScore}/10 ${this.getScoreEmoji(a.code.riskScore)}

### Top Dependencies
${depsList}${moreText}

---`;
  }

  private insights(a: AnalysisResult): string {
    const strengths = a.strengths.map((s, i) => `${i + 1}. ${s}`).join("\n");
    const weaknesses = a.weaknesses.map((w, i) => `${i + 1}. ${w}`).join("\n");
    const recommendations = a.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n");

    return `## 💡 Key Insights

### ✅ Strengths
${strengths}

### ⚠️ Weaknesses
${weaknesses}

### 🎯 Recommendations
${recommendations}

---`;
  }

  private footer(a: AnalysisResult): string {
    return `---

_Generated by **DevScout** | Powered by Zypher Agent Framework_
_Timestamp: ${new Date(a.analyzedAt).toISOString()}_`;
  }

  private formatNumber(num: number): string {
    if (num >= 1000000) {
      return `${(num / 1000000).toFixed(1)}M`;
    }
    if (num >= 1000) {
      return `${(num / 1000).toFixed(1)}K`;
    }
    return num.toString();
  }

  private getScoreEmoji(score: number): string {
    if (score >= 9) return "🌟";
    if (score >= 8) return "✅";
    if (score >= 7) return "👍";
    if (score >= 6) return "👌";
    if (score >= 5) return "😐";
    return "⚠️";
  }

  private getRating(score: number): string {
    if (score >= 9) return "Excellent";
    if (score >= 8) return "Very Good";
    if (score >= 7) return "Good";
    if (score >= 6) return "Above Average";
    if (score >= 5) return "Average";
    return "Below Average";
  }

  private getSentimentEmoji(sentiment: string): string {
    switch (sentiment) {
      case "positive":
        return "😊";
      case "negative":
        return "😞";
      case "mixed":
        return "🤔";
      default:
        return "😐";
    }
  }
}
