import type { JobAnalysis } from "../types/index.ts";

export class ReportBuilder {
  generate(a: JobAnalysis): string {
    const sections = [
      this.header(a),
      this.bullets(a),
      this.coverLetter(a),
      this.skills(a),
      this.footer(a),
    ];
    return sections.join("\n\n");
  }

  private header(a: JobAnalysis): string {
    return `# 🧭 DevScout Job Analysis

**Company**: ${a.job.company}
**Role**: ${a.job.role}
**Location**: ${a.job.location}
**Application**: ${a.job.applicationUrl}
**Source**: ${a.job.sourceUrl}`;
  }

  private bullets(a: JobAnalysis): string {
    const items = a.tailoredBullets.map((b, i) => `${i + 1}. ${b}`).join("\n");
    return `## Tailored Bullets

${items}`;
  }

  private coverLetter(a: JobAnalysis): string {
    return `## Cover Letter Draft

${a.coverLetter}`;
  }

  private skills(a: JobAnalysis): string {
    return `## Missing Skills

${a.missingSkills.length ? a.missingSkills.map((s, i) => `${i + 1}. ${s}`).join("\n") : "None reported."}`;
  }

  private footer(_a: JobAnalysis): string {
    return `

_Generated by DevScout | Powered by Zypher_`;
  }
}
